version: '3'

services:
  nginx-amplify:
    build:
      context: .
    environment:
      - API_KEY=${API_KEY}
      - AMPLIFY_IMAGENAME=example-web-server
    container_name: nginx-amplify
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "80:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
